### ISSUE TITLE
상세 modal 페이지 이벤트 구현

### ISSUE THREAD

**Issue by ha3158987** [ha3158987/sidedish#16]
1.  썸네일 클릭 시 메인 이미지와 스위칭
2.  상품 수량 변경 이벤트
    - 최초에 받은 가격을 기준으로 계산 (api 요청 x)
3.  주문하기 버튼 이벤트
    - api 요청 후 주문하기 결과 UI 출력

**Comment by kowoohyuk** [comment]
주문하기 버튼 이벤트 및 상품 수량 변경 이벤트는 리팩토링과 함께 진행!
